== Introducing PICKitPlus

PICKitPlus is software that interfaces with the PICKit2 and PICkit3 device programmers.

PICKitPlus software enables you to easily program, read and verify your projects code when using microcontrollers and EEPROMs.

The PICKitPlus development team also design and manufacture hardware like LCD controllers and sensors that make IoT development easier.

PICKitPlus software aims to help you avoid the complexities of complex software by making things easy.&#160;&#160;
Our software is the easiest way to work with microcontrollers and EEPROMs.&#160;&#160;
PICKitPlus software leverages the investment made in the PICKit 2 and PICKit 3 programmers to reduce the learning curve and the development time, and our hardware solutions are kits that are easy to build then you can integrate the solutions into your projects.

The PICKitPlus development team are UK based team.&#160;&#160;
We design, develop and support our solutions from the UK.&#160;&#160;
We operate UK business hours, but, to fulfill the needs of the global customers we are often available out of hours.


{empty} +

*PICKitPlus portfolio of applications*

Our software supports  Windows XP to Windows 10, Linux and Raspberry Pi.&#160;&#160;
To see the specifics of an application use this Help.&#160;&#160;

We support our portfolio applications and the associated parts database&#160;&#160;-&#160;&#160;we license per named user, the license  includes one year of application support and we also provide free updates to the parts database as we add more parts.

{empty} +

*Contacting the PICKitPlus development team*

Email on pickitplus@anobium.co.uk, or,

You can call us on +44 (0)1483 610159 24 hours a day, if we are there, we will answer, else, leave us a message with your contact information and we can get back to you.


